//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBuddy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoBuddy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;tree&quot;: [ { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;LANE&quot;, &quot;JUNGLE&quot; ], &quot;header&quot;: &quot;START&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;CONSUMABLE&quot;, &quot;GOLDPER&quot;, &quot;VISION&quot; ], &quot;header&quot;: &quot;TOOLS&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;HEALTH&quot;, &quot;ARMOR&quot;, &quot;SPELLBLOCK&quot;, &quot;HEALTHREGEN&quot; ], &quot;header&quot;: &quot;DEFENSE&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;DAMAGE&quot;, &quot;CRITICALSTRIKE&quot;, &quot;ATTACKSPEED&quot;, &quot;LIFESTEAL&quot; ], &quot;header&quot;: &quot;ATTACK&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;SPELLDAMAGE&quot;, &quot;COOLDOWNREDUCTION&quot;, &quot;MANA&quot;, &quot;MANAREGEN&quot; ], &quot;header&quot;: &quot;MAGIC&quot; }, { &quot;tags&quot;: [ &quot;_SORTINDEX&quot;, &quot;BOOTS&quot;, &quot;NO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NavGraphSummonersRift {
            get {
                object obj = ResourceManager.GetObject("NavGraphSummonersRift", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NavGraphSummonersRiftOld {
            get {
                object obj = ResourceManager.GetObject("NavGraphSummonersRiftOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
